import { TargetMarket } from "@/lib/types";

export type SeedCompany = {
  name: string;
  industry: string;
  regions: TargetMarket[];
  isFintechRelevant: boolean;
  isRiskRelevant: boolean;
  hasNewGradPipeline: boolean;
  recommendationNote: string;
  careersUrl?: string;
  isUserPriority?: boolean;
};

const ALL_MARKETS: TargetMarket[] = [
  "New York City",
  "San Francisco Bay Area",
  "Chicago",
  "Seattle",
  "North Carolina",
];

/**
 * Seed dataset for the company-recommendation engine. This is intentionally
 * a starting point, not exhaustive — expand it by editing this file (or,
 * later, by adding rows through a small admin UI). ATS provider/slug info
 * is deliberately NOT included here: guessing a company's ATS tenant slug
 * risks pointing users at a wrong or dead endpoint. Configure real,
 * verified ATS slugs in src/lib/companies/atsConfig.json instead.
 */
export const SEEDED_COMPANIES: SeedCompany[] = [
  // --- Default priority companies for this user (known internship/target relevance) ---
  {
    name: "JPMorgan Chase",
    industry: "Banking and financial institutions",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote:
      "Large bank with a well-known technology analyst / early-career program and strong risk-technology hiring — directly relevant to the Wells Fargo Risk Management internship.",
    careersUrl: "https://careers.jpmorgan.com",
    isUserPriority: true,
  },
  {
    name: "Salesforce",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote:
      "Major enterprise software company with an established new-grad / university program in software engineering and data roles.",
    careersUrl: "https://careers.salesforce.com",
    isUserPriority: true,
  },
  {
    name: "Citibank",
    industry: "Banking and financial institutions",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote:
      "Global bank with technology and risk-analyst early-career pipelines relevant to a Risk Management background.",
    careersUrl: "https://jobs.citi.com",
    isUserPriority: true,
  },

  // --- Banks and financial institutions ---
  {
    name: "Wells Fargo",
    industry: "Banking and financial institutions",
    regions: ALL_MARKETS,
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Prior internship employer — Risk Management relevance is direct.",
    careersUrl: "https://www.wellsfargojobs.com",
  },
  {
    name: "Goldman Sachs",
    industry: "Banking and financial institutions",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Strong technology-analyst and engineering campus program.",
    careersUrl: "https://www.goldmansachs.com/careers",
  },
  {
    name: "Morgan Stanley",
    industry: "Banking and financial institutions",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Technology and risk analyst early-career hiring in NYC.",
    careersUrl: "https://www.morganstanley.com/careers",
  },
  {
    name: "Bank of America",
    industry: "Banking and financial institutions",
    regions: ["New York City", "Chicago"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Technology and global risk analyst programs.",
    careersUrl: "https://careers.bankofamerica.com",
  },
  {
    name: "American Express",
    industry: "Banking and financial institutions",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Data and risk analytics roles with new-grad hiring.",
    careersUrl: "https://www.americanexpress.com/careers",
  },

  // --- Fintech and payments ---
  {
    name: "Capital One",
    industry: "Fintech and payments",
    regions: ["New York City", "Chicago"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Technology-forward bank with strong SWE/data new-grad pipeline and risk-tech overlap.",
    careersUrl: "https://www.capitalonecareers.com",
  },
  {
    name: "Visa",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Payments infrastructure with fraud/risk technology roles.",
    careersUrl: "https://usa.visa.com/careers.html",
  },
  {
    name: "PayPal",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Risk and fraud engineering roles alongside SWE new-grad hiring.",
    careersUrl: "https://careers.pypl.com",
  },
  {
    name: "Stripe",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "High-growth fintech infrastructure company with SWE new-grad hiring.",
    careersUrl: "https://stripe.com/jobs",
  },
  {
    name: "Plaid",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Financial data infrastructure fintech.",
    careersUrl: "https://plaid.com/careers",
  },
  {
    name: "Chime",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Consumer fintech with SWE/data hiring.",
    careersUrl: "https://www.chime.com/careers",
  },
  {
    name: "Affirm",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: false,
    recommendationNote: "Credit/risk-modeling relevance for a risk-management background.",
    careersUrl: "https://www.affirm.com/careers",
  },
  {
    name: "SoFi",
    industry: "Fintech and payments",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: false,
    recommendationNote: "Consumer lending fintech with credit-risk relevance.",
    careersUrl: "https://www.sofi.com/careers",
  },

  // --- Market data and financial technology ---
  {
    name: "Bloomberg",
    industry: "Market data and financial technology",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Well-known SWE/data new-grad program (BEST) in NYC.",
    careersUrl: "https://www.bloomberg.com/careers",
  },
  {
    name: "FactSet",
    industry: "Market data and financial technology",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Financial data platform with entry-level analyst/engineering hiring.",
    careersUrl: "https://www.factset.com/careers",
  },
  {
    name: "S&P Global",
    industry: "Market data and financial technology",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Ratings/risk data relevance plus data/software roles.",
    careersUrl: "https://careers.spglobal.com",
  },
  {
    name: "Moody's",
    industry: "Market data and financial technology",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Credit-risk and ratings analytics — direct overlap with risk-management background.",
    careersUrl: "https://careers.moodys.com",
  },
  {
    name: "Nasdaq",
    industry: "Market data and financial technology",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Market-technology roles with entry-level software hiring.",
    careersUrl: "https://www.nasdaq.com/about/careers",
  },
  {
    name: "Fiserv",
    industry: "Market data and financial technology",
    regions: ["Chicago"],
    isFintechRelevant: true,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Payments/fintech infrastructure employer.",
    careersUrl: "https://www.fiserv.com/en/about-fiserv/careers.html",
  },

  // --- Insurance and risk technology ---
  {
    name: "Aon",
    industry: "Insurance and risk technology",
    regions: ["Chicago"],
    isFintechRelevant: false,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Risk-consulting firm with analyst-level early-career hiring.",
    careersUrl: "https://www.aon.com/careers",
  },
  {
    name: "Travelers",
    industry: "Insurance and risk technology",
    regions: ["New York City"],
    isFintechRelevant: false,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Insurance risk-analyst and technology development programs.",
    careersUrl: "https://careers.travelers.com",
  },
  {
    name: "Allstate",
    industry: "Insurance and risk technology",
    regions: ["Chicago"],
    isFintechRelevant: false,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Insurance risk/data analytics with new-grad rotational programs.",
    careersUrl: "https://www.allstate.com/careers",
  },
  {
    name: "Liberty Mutual",
    industry: "Insurance and risk technology",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Insurance/risk technology hiring with early-career programs.",
    careersUrl: "https://www.libertymutualgroup.com/careers",
  },

  // --- Technology companies ---
  {
    name: "Google",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area", "New York City", "Seattle"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Large-scale new-grad SWE/DS hiring across multiple target markets.",
    careersUrl: "https://careers.google.com",
  },
  {
    name: "Microsoft",
    industry: "Technology companies",
    regions: ["Seattle"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Headquartered near Seattle; strong university-hire SWE program.",
    careersUrl: "https://careers.microsoft.com",
  },
  {
    name: "Amazon",
    industry: "Technology companies",
    regions: ["Seattle"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "HQ market with high-volume new-grad SWE/DS hiring.",
    careersUrl: "https://www.amazon.jobs",
  },
  {
    name: "Meta",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "University-grad SWE/DS/ML hiring.",
    careersUrl: "https://www.metacareers.com",
  },
  {
    name: "Apple",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "New-grad SWE hiring in the Bay Area.",
    careersUrl: "https://www.apple.com/careers",
  },
  {
    name: "Oracle",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Enterprise software new-grad program.",
    careersUrl: "https://www.oracle.com/careers",
  },
  {
    name: "ServiceNow",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Enterprise SaaS with early-career SWE hiring.",
    careersUrl: "https://careers.servicenow.com",
  },
  {
    name: "Cisco",
    industry: "Technology companies",
    regions: ["San Francisco Bay Area", "North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Has an RTP, NC campus in addition to Bay Area HQ.",
    careersUrl: "https://jobs.cisco.com",
  },

  // --- Data, AI, and enterprise software ---
  {
    name: "Datadog",
    industry: "Data, AI, and enterprise software",
    regions: ["New York City"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "NYC-based infrastructure/monitoring company with SWE hiring.",
    careersUrl: "https://careers.datadoghq.com",
  },
  {
    name: "Snowflake",
    industry: "Data, AI, and enterprise software",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Data-platform company with new-grad SWE/DS hiring — good CS+DS fit.",
    careersUrl: "https://www.snowflake.com/careers",
  },
  {
    name: "Databricks",
    industry: "Data, AI, and enterprise software",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Data/ML platform with strong new-grad DS/ML relevance.",
    careersUrl: "https://www.databricks.com/company/careers",
  },
  {
    name: "MongoDB",
    industry: "Data, AI, and enterprise software",
    regions: ["New York City"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "NYC-based database company with SWE hiring.",
    careersUrl: "https://www.mongodb.com/careers",
  },
  {
    name: "Cloudflare",
    industry: "Data, AI, and enterprise software",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Infrastructure company with SWE hiring.",
    careersUrl: "https://www.cloudflare.com/careers",
  },
  {
    name: "Okta",
    industry: "Data, AI, and enterprise software",
    regions: ["San Francisco Bay Area"],
    isFintechRelevant: false,
    isRiskRelevant: true,
    hasNewGradPipeline: false,
    recommendationNote: "Identity/security relevance overlaps with risk/cyber interest.",
    careersUrl: "https://www.okta.com/careers",
  },

  // --- Consulting and professional services ---
  {
    name: "Deloitte",
    industry: "Consulting and professional services",
    regions: ["New York City", "Chicago"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Risk advisory practice with analyst-level new-grad hiring.",
    careersUrl: "https://www2.deloitte.com/us/en/careers.html",
  },
  {
    name: "EY",
    industry: "Consulting and professional services",
    regions: ["New York City"],
    isFintechRelevant: true,
    isRiskRelevant: true,
    hasNewGradPipeline: true,
    recommendationNote: "Financial-services risk advisory analyst hiring.",
    careersUrl: "https://www.ey.com/en_us/careers",
  },
  {
    name: "Accenture",
    industry: "Consulting and professional services",
    regions: ["Chicago", "North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Technology consulting with large analyst new-grad classes.",
    careersUrl: "https://www.accenture.com/us-en/careers",
  },

  // --- North Carolina employers ---
  {
    name: "Red Hat",
    industry: "North Carolina employers",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Raleigh-headquartered open-source software company.",
    careersUrl: "https://www.redhat.com/en/jobs",
  },
  {
    name: "SAS",
    industry: "North Carolina employers",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: true,
    recommendationNote: "Cary, NC analytics/AI software company — strong CS+DS fit.",
    careersUrl: "https://www.sas.com/en_us/careers.html",
  },
  {
    name: "Epic Games",
    industry: "North Carolina employers",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Cary, NC-headquartered SWE employer.",
    careersUrl: "https://www.epicgames.com/site/en-US/careers",
  },
  {
    name: "Bandwidth",
    industry: "North Carolina employers",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Raleigh-based communications software company.",
    careersUrl: "https://www.bandwidth.com/careers",
  },
  {
    name: "IQVIA",
    industry: "North Carolina employers",
    regions: ["North Carolina"],
    isFintechRelevant: false,
    isRiskRelevant: false,
    hasNewGradPipeline: false,
    recommendationNote: "Durham-area health-data analytics employer — good DS fit.",
    careersUrl: "https://jobs.iqvia.com",
  },
];
